version: '2'
volumes:
    config:
    mosquitto:
    mqttio:
services:
  homeassistant:
    build: homeassistant
    ports:
      - "1900:1900"
      - "1901:1901"
      - "80:8123"
      - "51827:51827"
    privileged: true
    volumes:
      - 'config:/config'
    restart: always
  mqtt:
    build: mqtt
    ports:
      - "1883:1883"
    restart: always
    volumes:
      - 'mosquitto:/mosquitto/data'
  hass-configurator:
    image: "causticlab/hass-configurator-docker:latest"
    restart: always
    ports:
      - "3218:3218"
    volumes:
      - 'config:/hass-config'
    environment:
      - HC_BASEPATH=/hass-config
#  mqttio_2:
#    image: "python:3.8.10-alpine"
#    volumes:
#      - "mqttio:/config"
#    privileged: true
#  mqtt-io_3:
#    build: mqtt_io_3
#    restart: always
#    privileged: true
#    volumes:
#      - 'mqttio:/config'

 